steps:
  # Build and push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ticketify-backend:$BUILD_ID', './Code/backend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ticketify-backend:$BUILD_ID']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'ticketify-backend',
      '--image', 'gcr.io/$PROJECT_ID/ticketify-backend:$BUILD_ID',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '2',
      '--max-instances', '10',
      '--set-env-vars', 'REDIS_URL=redis://10.0.0.3:6379/0,JWT_SECRET_KEY=your-production-secret-key-here'
    ]

options:
  logging: CLOUD_LOGGING_ONLY 