[build]
  # Directory to change to before starting a build
  base = "Code/frontend-vite"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "Code/frontend-vite/dist"
  
  # Default build command
  command = "npm ci && npm run build"

[build.environment]
  # Node.js version for the build
  NODE_VERSION = "18"
  
  # API URL for production (pointing to your Google Cloud Run backend)
  VITE_API_URL = "https://ticketify-backend-321805997355.us-central1.run.app"

[[redirects]]
  # Handle client-side routing for Vue.js SPA
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Apply headers to all routes
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets for 1 year
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Don't cache the main HTML file
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 